url: https://equippers.de
timezone: Europe/Berlin

permalink: /blog/:year/:month/:title

exclude:
  - 'node_modules'
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.tsbuildinfo'

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: base
  - scope:
      path: 'berlin'
      type: 'pages'
    values:
      layout: 'berlin'
      title_suffix: 'Gottesdienst in Berlin'
  - scope:
      path: 'hamburg'
      type: 'pages'
    values:
      layout: 'hamburg'
  - scope:
      path: 'muenchen'
      type: 'pages'
    values:
      layout: 'muenchen'

# --
# Cloudcannon

_options:
  hero_image:
    uploads_dir: 'uploads/hero'

icon_ids:
  - facebook
  - instagram
  - twitter
  - newsletter
  - podcast

# --
# Assets

stylus:
  compress: false # Cloudcannon will do the compression
  path: styles
