import { initMap } from './init-map';
import { loadScripts } from './load-scripts';
import { renderRecaptchas } from './render-recaptchas';
import { setUpForms } from './set-up-forms';
import { toggleModal } from './toggle-modal';
import { stopModalContentPropagation } from './utils';

export interface Group {
	name: string;
	leader: string;
	modalId: string;
	locationId: string;
	pos: google.maps.LatLngLiteral;
}

/**
 * The markers are generated by the template into the global scope.
 */
declare const groups: Group[];

(window as any).toggleModal = toggleModal;
if (groups.length) {
	(window as any).initMap = initMap(groups);
}
const isSistasWebsite = window.location.href.includes('sistas');
// BIG HACK... remove ASAP!
if (!isSistasWebsite) {
	(window as any).renderRecaptchas = renderRecaptchas(groups);
}

stopModalContentPropagation();
setUpForms(groups);

const eGroupsGDPRAccepted = localStorage.getItem('egroups-gdpr-accepted') && window.location.href.includes('egroups');
if (eGroupsGDPRAccepted || isSistasWebsite) {
	loadScripts(isSistasWebsite);
} else {
	document.querySelector('#gdpr button' as 'button')?.addEventListener('click', () => {
		// Sistas website has no gdpr button as yet
		loadScripts(false);
	});
}
